name: "Test PyPI Token"

on:
  workflow_dispatch:

permissions: write-all

jobs:
  test_pypi_token:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: "Test PyPI Token with twine"
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          echo "[distutils]" > ~/.pypirc
          echo "index-servers = pypi" >> ~/.pypirc
          echo "[pypi]" >> ~/.pypirc
          echo "username = $TWINE_USERNAME" >> ~/.pypirc
          echo "password = $TWINE_PASSWORD" >> ~/.pypirc
          python -m pip install --upgrade pip twine
          # Create a dummy package
          mkdir testpkg && cd testpkg
          echo "from setuptools import setup; setup(name='testpkg', version='0.0.1')" > setup.py
          python setup.py sdist
          # Try to upload to PyPI (will fail if token is invalid)
          twine upload --repository pypi dist/* --non-interactive --skip-existing || echo "PyPI token test completed."
